import { format } from "date-fns"
import type { Booking } from "@/services/bookingService"

interface InvoicePDFProps {
  data: Booking & { invoiceNumber?: string; clientCode?: string; clientAddress?: string; dueDate?: string }
  amountPaid?: number
}
const teal = "#008fa3"
function euros(value: number) { return `${value.toLocaleString("fr-FR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}€` }

export function InvoicePDF({ data, amountPaid = 0 }: InvoicePDFProps) {
  const totalTTC = Number(data.total || 0), totalHT = totalTTC / 1.2, vat = totalTTC - totalHT
  const isPaid = totalTTC > 0 && amountPaid >= totalTTC
  const number = data.invoiceNumber || `${format(new Date(), "yyyy")}${String(data.id).replace(/\D/g, "").slice(-3).padStart(3, "0")}`
  const clientAddress = data.clientAddress || data.originAddress
  return <section data-pdf-page className="relative bg-white text-[11px]" style={{ width: "210mm", height: "297mm", padding: "10mm 13mm", boxSizing: "border-box", fontFamily: "Arial, Helvetica, sans-serif", color: teal, overflow: "hidden" }}>
    <div className="grid grid-cols-[1fr_78mm] gap-8">
      <div><img src="/images/logo.png" alt="Déménagement du Vexin" style={{ width: "82mm", height: "auto" }} /><div className="mt-2 font-bold leading-[1.45]">9 RUE DE PONTOISE<br />95540 MÉRY-SUR-OISE<br />Tel: &nbsp;&nbsp;&nbsp;01 30 75 12 35<br />Mob: &nbsp;07 68 31 33 10<br />e-mail: demenagementduvexin@gmail.com</div></div>
      <div className="space-y-3 text-center italic" style={{ fontFamily: "Georgia, serif" }}><div className="rounded-[18px] border border-black p-3 leading-[1.45]"><strong>Facture N° {number}</strong><br />Date: {format(new Date(), "dd/MM/yyyy")}<br />Code client:{data.clientCode || "À CRÉER"}<br /><small>Date limite de paiement :30 jours</small></div><div className="min-h-[35mm] rounded-[18px] border border-black p-3 leading-[1.5]"><span className="underline">Adresse du Client</span><br />{data.clientName}<br />{clientAddress}</div></div>
    </div>
    <table className="mt-5 w-full table-fixed border-collapse"><thead><tr className="text-white"><th className="w-[52%] border border-black p-2" style={{ background: teal, fontFamily: "Georgia, serif", fontSize: "13px" }}>Désignation</th><th className="w-[16%] border border-black p-2" style={{ background: teal, fontFamily: "Georgia, serif", fontSize: "13px" }}>Quantité</th><th className="w-[17%] border border-black p-2" style={{ background: teal, fontFamily: "Georgia, serif", fontSize: "13px" }}>Prix unitaire</th><th className="w-[15%] border border-black p-2" style={{ background: teal, fontFamily: "Georgia, serif", fontSize: "13px" }}>Total HT</th></tr></thead><tbody><tr className="h-[73mm] align-top italic"><td className="border border-black p-2 leading-[1.5]">Chargement effectué le {format(new Date(data.moveDate), "dd/MM/yyyy")}<br />Distance : {data.distance || "-"} KM<br />Volume : {data.volume} M3<br />Déchargement effectué à l’adresse prévue<br /><br />{data.originAddress}<br />{data.destinationAddress}</td><td className="border border-black p-2 text-center">{data.volume}m³</td><td className="border border-black p-2" /><td className="border border-black p-2 text-right">{euros(totalHT)}</td></tr></tbody></table>
    <div className="flex items-start justify-between"><div className="pl-2 pt-10 text-[19px] italic" style={{ color: isPaid ? "red" : teal, fontFamily: "Georgia, serif" }}>{isPaid ? "Facture acquittée" : `Reste à payer : ${euros(Math.max(totalTTC - amountPaid, 0))}`}</div><table className="w-[59mm] border-collapse"><tbody><tr><td className="border border-black p-1 text-white" style={{ background: teal }}>Total HT</td><td className="border border-black p-1 text-right font-bold italic">{euros(totalHT)}</td></tr><tr><td className="border border-black p-1 text-white" style={{ background: teal }}>TVA 20 %</td><td className="border border-black p-1 text-right italic">{euros(vat)}</td></tr><tr><td className="border border-black p-1 font-bold text-white" style={{ background: teal }}>À payer TTC</td><td className="border border-black p-1 text-right font-bold italic">{euros(totalTTC)}</td></tr><tr className="h-8"><td className="border border-black" style={{ background: teal }} /><td className="border border-black" /></tr></tbody></table></div>
    <div className="mt-12 text-[9px]"><span className="px-1 font-bold text-white" style={{ background: teal }}>Relevé d’identité bancaire</span><table className="mt-4 w-full text-center"><thead><tr className="text-white" style={{ background: teal }}><th>Titulaire du compte</th><th>Code Banque</th><th>Code Guichet</th><th>Numéro de compte</th><th>Clé RIB</th><th>Domiciliation</th></tr></thead><tbody><tr><td>D D V</td><td>30066</td><td>10461</td><td>00020606102</td><td>84</td><td>CIC PONTOISE</td></tr></tbody></table><table className="mt-4 w-full text-center"><thead><tr className="text-white" style={{ background: teal }}><th>Identifiant international de compte bancaire-IBAN</th><th>Identification international de l’établissement bancaire-BIC</th></tr></thead><tbody><tr><td>FR76 3006 6104 6100 0206 0610 284</td><td>SWIFT BIC : CMCIFRPP</td></tr></tbody></table></div>
    <div className="mt-6 text-center text-[8px] leading-[1.4]">Date de règlement: maximum 30 jours après la date d’émission de la facture (la date limite de paiement doit être précisée sur la facture)<br />En cas de défaut de paiement dans le délai prévu sur cette facture, nous appliquerons une pénalité égale à 3x le taux d’intérêt légal.</div>
    <div className="absolute bottom-[20mm] left-0 right-0 text-center text-[10px] italic" style={{ fontFamily: "Georgia, serif" }}>SASU AU CAPITAL DE 27 000 € RCS PONTOISE SIRET &nbsp;895 250 579 00011 N° TVA : FR3589520579</div>
  </section>
}
